#!/usr/bin/python2.1

import GopherFiles
import cgi

form = cgi.FieldStorage()
gopherobj = GopherFiles.GopherFile()
if form.has_key("selector") and form.has_key("host") and \
   form.has_key("username") and form.has_key("port") and \
   form.has_key("type"):
    gopherobj.setselector(form['selector'].value)
    gopherobj.sethost(form['host'].value)
    gopherobj.setusername(form['username'].value)
    gopherobj.setport(int(form['port'].value))
    gopherobj.settype(form['type'].value)
else:
    gopherobj.setselector('')
    gopherobj.sethost('quux.org')
    gopherobj.setport(70)
    gopherobj.setusername('')
    gopherobj.settype('1')

gopherobj.rebless()
gopherobj.display()



