#!/usr/bin/python2.1

from GopherFiles import GopherFileDir

gd = GopherFileDir()
gd.setselector('')
gd.sethost('quux.org')
gd.setport(70)
gd.setusername('')
gd.getfromnet()

for entry in gd:
    print entry.getHTMLdirline() + "<BR>"



