#!/usr/bin/python2.1

# $Id: hurg,v 1.9 2001/08/29 18:18:55 jgoerzen Exp $

# The file is part of HURG
# Copyright (C) 2001 John Goerzen
# jgoerzen@complete.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import GopherFiles
import cgi
import socket
import sys
import traceback
import os

def populate(gopherobj, form):
    gopherobj.setselector(form['selector'].value)
    gopherobj.sethost(form['host'].value)
    gopherobj.setusername(form['username'].value)
    gopherobj.setport(int(form['port'].value))
    gopherobj.settype(form['type'].value)

def errorpage(message, tb):
    print 'Content-Type: text/html'
    print
    print '<HTML><BODY><H1>HURG Error</H1><PRE>'
    print message
    # traceback.print_exc(file=sys.stdout)
    print '</PRE></BODY></HTML>'
    sys.exit(0)

form = cgi.FieldStorage(keep_blank_values=1)
if form.has_key("cmd"):
    if (form['cmd'].value == 'open'):
        print "Content-Type: text/html"
        print
        print """<HTML><HEAD><TITLE>HURG: Open</TITLE></HEAD><BODY>
        <FORM METHOD=GET ACTION="hurg">
        <INPUT TYPE=hidden NAME=username VALUE=" ">
        Host: <INPUT TYPE=text NAME=host><BR>
        Port: <INPUT TYPE=text NAME=port VALUE="70"><BR>
        Type: <INPUT TYPE=text NAME=type VALUE="1" WIDTH=1><BR>
        Selector: <INPUT TYPE=text NAME=selector><BR>
        <INPUT TYPE=submit NAME=Submit VALUE=Submit>
        </FORM></BODY></HTML>"""
    elif (form['cmd'].value == 'about'):
        gopherobj = GopherFiles.GopherFile()
        populate(gopherobj, form)
        print "Content-Type: text/html"
        print
        print """<HTML><HEAD><TITLE>HURG: About</TITLE></HEAD><BODY>
        <H1>HURG: About Link</H1>
        Did you mean to follow a link?  If so, use your browser's back
        button and then click on the document name instead of the icon.
        Or, click
        <A HREF="%s">here</A>.<P>
        <TABLE>
        <TR><TD><B>Link Name:</B></TD><TD>%s</TD></TR>
        <TR><TD><B>Host:</B></TD><TD>%s</TD></TR>
        <TR><TD><B>Port:</B></TD><TD>%s</TD></TR>
        <TR><TD><B>Selector:</B></TD><TD>%s</TD></TR>
        <TR><TD><B>Gopher type:</B></TD><TD>%s</TD></TR>
        <TR><TD><B>HTTP Content type:</B></TD><TD>%s</TD></TR>
        </TABLE></BODY></HTML>
        """ % (gopherobj.getHTMLlink(), gopherobj.getusername(),
               gopherobj.gethost(),
               gopherobj.getport(), gopherobj.getselector(),
               gopherobj.gettype(), gopherobj.getcontenttype())
else:
    gopherobj = GopherFiles.GopherFile()
    if form.has_key("selector") and form.has_key("host") and \
       form.has_key("username") and form.has_key("port") and \
       form.has_key("type"):
        populate(gopherobj, form)
    else:
        gopherobj.setselector('')
        gopherobj.sethost('gopher.quux.org')
        gopherobj.setport(70)
        gopherobj.setusername('Quux.Org')
        gopherobj.settype('1')

    if form.has_key("cannedspiel"):
        gopherobj.setspiel("""Welcome to Gopherspace!
        You are browsing Gopher through a Web gateway right now.  You can also
        use most browsers or Gopher clients to browse Gopher natively.
        If your browser supports it, try clicking on the "native view" link
        at the bottom of this page to see Gopher directly.
        To find Gopher browsers, <A HREF="%s">click here</A>.
        Enjoy your visit!<HR>""" %
                           GopherFiles.GopherFile('gopher.quux.org', 70,
                                      '1',
                                      '/Software/Gopher/Downloads/Clients',
                                      'Gopher Browsers').getHTMLlink())
        
    gopherobj.rebless()
    try:
        gopherobj.display()
    except IOError, (errno,):
        errorpage("I/O error: %s\n" % (errno),
                  sys.exc_info()[2])
    except socket.error, (errno):
        errorpage("Socket error: %s\n" % (errno),
                  sys.exc_info()[2])

